### ISSUE TITLE
Login command

### ISSUE THREAD

**Issue by evanp** [evanp/ap#4]

**Comment by rimu** [comment]
Can you give me an example login command I can run?

I've tried various things with no luck:

`❯ ./ap login
usage: ap login [-h] id
ap login: error: the following arguments are required: id
❯ ./ap login rimu@mastodon.nzoss.nz
Traceback (most recent call last):
  File "/home/rimu/Downloads/ap/./ap", line 222, in <module>
    main()
  File "/home/rimu/Downloads/ap/./ap", line 218, in main
    command.run()
  File "/home/rimu/Downloads/ap/commands/login.py", line 82, in run
    (auth_endpoint, token_endpoint) = self.oauth_endpoints(json)
  File "/home/rimu/Downloads/ap/commands/login.py", line 57, in oauth_endpoints
    raise Exception("No oauthAuthorizationEndpoint found")
Exception: No oauthAuthorizationEndpoint found
❯ ./ap login @rimu@mastodon.nzoss.nz
Traceback (most recent call last):
  File "/home/rimu/Downloads/ap/./ap", line 222, in <module>
    main()
  File "/home/rimu/Downloads/ap/./ap", line 218, in main
    command.run()
  File "/home/rimu/Downloads/ap/commands/login.py", line 82, in run
    (auth_endpoint, token_endpoint) = self.oauth_endpoints(json)
  File "/home/rimu/Downloads/ap/commands/login.py", line 57, in oauth_endpoints
    raise Exception("No oauthAuthorizationEndpoint found")
Exception: No oauthAuthorizationEndpoint found
❯ ./ap login mastodon.nzoss.nz
Traceback (most recent call last):
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/urllib3/util/url.py", line 425, in parse_url
    host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
AttributeError: 'NoneType' object has no attribute 'groups'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/requests/models.py", line 434, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/urllib3/util/url.py", line 451, in parse_url
    raise LocationParseError(source_url) from e
urllib3.exceptions.LocationParseError: Failed to parse: https://acct:mastodon.nzoss.nz/.well-known/webfinger

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rimu/Downloads/ap/./ap", line 222, in <module>
    main()
  File "/home/rimu/Downloads/ap/./ap", line 218, in main
    command.run()
  File "/home/rimu/Downloads/ap/commands/login.py", line 79, in run
    self.actor_id = self.get_actor_id(self.id)
  File "/home/rimu/Downloads/ap/commands/command.py", line 90, in get_actor_id
    wf = webfinger.finger(id)
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/webfinger.py", line 123, in finger
    return WebFingerClient().finger(resource, rel=rel)
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/webfinger.py", line 105, in finger
    resp = requests.get(url, params=params, headers=headers, timeout=self.timeout, verify=True)
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/rimu/Downloads/ap/venv/lib64/python3.9/site-packages/requests/models.py", line 436, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: https://acct:mastodon.nzoss.nz/.well-known/webfinger
`
