### ISSUE TITLE
test login command

### ISSUE THREAD

**Issue by evanp** [evanp/ap#46]

**Comment by naturzukunft** [comment]
Hi @evanp ,
i just tested the login. The actor is :
```
{
    "id": "https://dev.rdf-pub.org/actor/1813bdc1-152c-4c27-92a6-6cdfe401ef3d",
    "type": "Person",
    "inboxSparql": "https://dev.rdf-pub.org/actor/1813bdc1-152c-4c27-92a6-6cdfe401ef3d/inbox/sparql",
    "outboxSparql": "https://dev.rdf-pub.org/actor/1813bdc1-152c-4c27-92a6-6cdfe401ef3d/outbox/sparql",
    "identifier": "1813bdc1-152c-4c27-92a6-6cdfe401ef3d",
    "version": {
        "type": "xsd:integer",
        "@value": "1"
    },
    "inbox": "https://dev.rdf-pub.org/actor/1813bdc1-152c-4c27-92a6-6cdfe401ef3d/inbox",
    "endpoints": "https://dev.rdf-pub.org/actor/1813bdc1-152c-4c27-92a6-6cdfe401ef3d/objects/fd93e263-05ae-4d12-acfa-2fd92bf89e07",
    "outbox": "https://dev.rdf-pub.org/actor/1813bdc1-152c-4c27-92a6-6cdfe401ef3d/outbox",
    "preferredUsername": "max",
    "@context": [
        "https://schema.org/docs/jsonldcontext.json",
        "https://www.w3.org/ns/activitystreams",
        "https://rdf-pub.org/schema/rdf-pub-context.json"
    ]
}```
```
and the endpoints is:

```
{
    "id": "https://dev.rdf-pub.org/actor/1813bdc1-152c-4c27-92a6-6cdfe401ef3d/objects/fd93e263-05ae-4d12-acfa-2fd92bf89e07",
    "identifier": "0ac95648-2892-43f5-8952-d1e7756c6b8b",
    "version": {
        "type": "xsd:integer",
        "@value": "1"
    },
    "oauthAuthorizationEndpoint": "https://login.m4h.network/auth/realms/LOA/protocol/openid-connect/auth",
    "oauthTokenEndpoint": "https://login.m4h.network/auth/realms/LOA/protocol/openid-connect/token",
    "@context": [
        "https://schema.org/docs/jsonldcontext.json",
        "https://www.w3.org/ns/activitystreams",
        "https://rdf-pub.org/schema/rdf-pub-context.json"
    ]
}
```

Result:
```
ap$ ap login max@dev.rdf-pub.org
Traceback (most recent call last):
  File "/usr/local/bin/ap", line 33, in <module>
    sys.exit(load_entry_point('ap==0.1.0.dev0', 'console_scripts', 'ap')())
  File "/usr/local/lib/python3.10/dist-packages/ap-0.1.0.dev0-py3.10.egg/ap/main.py", line 299, in main
  File "/usr/local/lib/python3.10/dist-packages/ap-0.1.0.dev0-py3.10.egg/ap/main.py", line 294, in run_command
  File "/usr/local/lib/python3.10/dist-packages/ap-0.1.0.dev0-py3.10.egg/ap/commands/login.py", line 82, in run
  File "/usr/local/lib/python3.10/dist-packages/ap-0.1.0.dev0-py3.10.egg/ap/commands/login.py", line 55, in oauth_endpoints
AttributeError: 'str' object has no attribute 'get'
```

**Comment by evanp** [comment]
I don't think "endpoints" can be an URL. But I should add a check for this.

**Comment by naturzukunft** [comment]
[endpoints](https://www.w3.org/TR/activitypub/#actor-objects)
A json object which maps additional (typically server/domain-wide) endpoints which may be useful either for this actor or someone referencing this actor. This mapping may be nested inside the actor document as the value **or may be a link to a JSON-LD document with these properties**. 

For me _A json object_ is a wrong therm here. It should be _A JSON-LD object_.

**Comment by naturzukunft** [comment]
See also [this discussion](https://socialhub.activitypub.rocks/t/blank-nodes-object-identifiers/3617/1) regarding blank nodes.
