### ISSUE TITLE
ap login example

### ISSUE THREAD

**Issue by mattcam** [evanp/ap#72]
A step by step `ap login` example would be very helpful.

I'm struggling to understand how to use the command `ap login`.

Thanks

**Comment by gobengo** [comment]
This is what I get
```
⚡ ap login 'https://mastodon.social/@bengo'
Traceback (most recent call last):
  File "/opt/homebrew/bin/ap", line 33, in <module>
    sys.exit(load_entry_point('ap==0.3.0', 'console_scripts', 'ap')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/ap-0.3.0-py3.12.egg/ap/main.py", line 316, in main
  File "/opt/homebrew/lib/python3.12/site-packages/ap-0.3.0-py3.12.egg/ap/main.py", line 311, in run_command
  File "/opt/homebrew/lib/python3.12/site-packages/ap-0.3.0-py3.12.egg/ap/commands/login.py", line 75, in run
  File "/opt/homebrew/lib/python3.12/site-packages/ap-0.3.0-py3.12.egg/ap/commands/login.py", line 52, in oauth_endpoints
  File "/opt/homebrew/lib/python3.12/site-packages/ap-0.3.0-py3.12.egg/ap/commands/command.py", line 250, in get_endpoint
Exception: No oauthAuthorizationEndpoint found
```
